### ISSUE TITLE
Throttling notifications

### ISSUE THREAD

**Issue by tilsche** [metricq/metricq-sink-nsca#28]
Not sure what exactly is going wrong, but today it seems 13k notifications were created for the elab checks within 25 minutes...

Whatever the circumstances, this must not happen.

Rumor has it, if noone cleared the backlog Centreon is still be sending mails right now...

**Comment by phijor** [comment]
After review, it seems like this was caused by a combination of #29 and a client misconfiguration. The client's checks should have set a `transition_debounce_window`. Without it, the checker reported alternating check results of `OK` and `CRITCAL`. These state changes happened way to quickly because of lingering `TimeoutChecks` (#29), and resulted in a flood of notifications.

I am keeping this open until at least #29 is fixed.
